// <auto-generated />
using System;
using AstralDiaryApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AstralDiaryApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260402014303_RemovedTitleContent")]
    partial class RemovedTitleContent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AstralDiaryApi.Models.Entities.Draft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachmentHash")
                        .HasColumnType("longtext")
                        .HasColumnName("attachment_hash");

                    b.Property<string>("AttachmentId")
                        .HasColumnType("longtext")
                        .HasColumnName("attachment_id");

                    b.Property<string>("AttachmentPath")
                        .HasColumnType("longtext")
                        .HasColumnName("att_file_path");

                    b.Property<string>("ContentIv")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("content_iv");

                    b.Property<string>("ContentSalt")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("content_salt");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("EncryptedContent")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("encrypted_content");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("draft_id");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("modified_at");

                    b.Property<int>("Mood")
                        .HasColumnType("int")
                        .HasColumnName("mood");

                    b.Property<string>("ThumbnailPath")
                        .HasColumnType("longtext")
                        .HasColumnName("att_thumbnail_path");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.HasIndex("ModifiedAt");

                    b.HasIndex("UserId");

                    b.ToTable("Drafts");
                });

            modelBuilder.Entity("AstralDiaryApi.Models.Entities.Entry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachmentHash")
                        .HasColumnType("longtext")
                        .HasColumnName("attachment_hash");

                    b.Property<string>("AttachmentId")
                        .HasColumnType("longtext")
                        .HasColumnName("attachment_id");

                    b.Property<string>("AttachmentPath")
                        .HasColumnType("longtext")
                        .HasColumnName("att_file_path");

                    b.Property<string>("ContentIv")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("content_iv");

                    b.Property<string>("ContentSalt")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("content_salt");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("deleted_at");

                    b.Property<string>("EncryptedContent")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("encrypted_content");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("entry_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("modified_at");

                    b.Property<int>("Mood")
                        .HasColumnType("int")
                        .HasColumnName("mood");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("published_at");

                    b.Property<string>("ThumbnailPath")
                        .HasColumnType("longtext")
                        .HasColumnName("att_thumbnail_path");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("EntityId");

                    b.HasIndex("Mood");

                    b.HasIndex("UserId");

                    b.ToTable("Entries", t =>
                        {
                            t.HasCheckConstraint("CK_Entry_DeletedAt_OnlyIf_IsDeleted", "(is_deleted = 1 AND deleted_at IS NOT NULL) OR (is_deleted = 0 AND deleted_at IS NULL)");
                        });
                });

            modelBuilder.Entity("AstralDiaryApi.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasColumnType("longtext")
                        .HasColumnName("avatar");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("FirebaseUid")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("firebase_uid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AstralDiaryApi.Models.Entities.Draft", b =>
                {
                    b.HasOne("AstralDiaryApi.Models.Entities.User", "User")
                        .WithMany("Drafts")
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AstralDiaryApi.Models.Entities.Entry", b =>
                {
                    b.HasOne("AstralDiaryApi.Models.Entities.User", "User")
                        .WithMany("Entries")
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AstralDiaryApi.Models.Entities.User", b =>
                {
                    b.Navigation("Drafts");

                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
