// <auto-generated />
using System;
using AstralDiaryApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AstralDiaryApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260316231335_AddedHideDeletedInQuery")]
    partial class AddedHideDeletedInQuery
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AstralDiaryApi.Models.Entities.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("content_hash");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DraftId")
                        .HasColumnType("varchar(25)")
                        .HasColumnName("draft_id");

                    b.Property<string>("EntryId")
                        .HasColumnType("varchar(25)")
                        .HasColumnName("entry_id");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("file_path");

                    b.Property<string>("InternalFileName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("internal_name");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("original_name");

                    b.Property<string>("ThumbnailPath")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("thumbnail_path");

                    b.HasKey("Id");

                    b.HasIndex("DraftId");

                    b.HasIndex("EntryId");

                    b.HasIndex("InternalFileName");

                    b.ToTable("Attachments", t =>
                        {
                            t.HasCheckConstraint("CK_Attachment_SingleSource", "(entry_id IS NULL AND draft_id IS NOT NULL) OR (entry_id IS NOT NULL AND draft_id IS NULL)");
                        });
                });

            modelBuilder.Entity("AstralDiaryApi.Models.Entities.Draft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("longtext")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("draft_id");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("modified_at");

                    b.Property<string>("Title")
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.HasIndex("ModifiedAt");

                    b.HasIndex("UserId");

                    b.ToTable("Drafts");
                });

            modelBuilder.Entity("AstralDiaryApi.Models.Entities.Entry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("deleted_at");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("entry_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("modified_at");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("published_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("EntityId");

                    b.HasIndex("UserId");

                    b.HasIndex("Title", "Content")
                        .HasAnnotation("MySql:FullTextIndex", true);

                    b.ToTable("Entries", t =>
                        {
                            t.HasCheckConstraint("CK_Entry_DeletedAt_OnlyIf_IsDeleted", "(is_deleted = 1 AND deleted_at IS NOT NULL) OR (is_deleted = 0 AND deleted_at IS NULL)");
                        });
                });

            modelBuilder.Entity("AstralDiaryApi.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("FirebaseUid")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("firebase_uid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AstralDiaryApi.Models.Entities.Attachment", b =>
                {
                    b.HasOne("AstralDiaryApi.Models.Entities.Draft", "Draft")
                        .WithMany("Attachments")
                        .HasForeignKey("DraftId")
                        .HasPrincipalKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AstralDiaryApi.Models.Entities.Entry", "Entry")
                        .WithMany("Attachments")
                        .HasForeignKey("EntryId")
                        .HasPrincipalKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Draft");

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("AstralDiaryApi.Models.Entities.Draft", b =>
                {
                    b.HasOne("AstralDiaryApi.Models.Entities.User", "User")
                        .WithMany("Drafts")
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AstralDiaryApi.Models.Entities.Entry", b =>
                {
                    b.HasOne("AstralDiaryApi.Models.Entities.User", "User")
                        .WithMany("Entries")
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AstralDiaryApi.Models.Entities.Draft", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("AstralDiaryApi.Models.Entities.Entry", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("AstralDiaryApi.Models.Entities.User", b =>
                {
                    b.Navigation("Drafts");

                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
