// <auto-generated />
using System;
using AstralDiaryApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AstralDiaryApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260223235907_AddedCreatedAtInAttachmentTable")]
    partial class AddedCreatedAtInAttachmentTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AstralDiaryApi.Models.Entities.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DraftId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("draft_id");

                    b.Property<string>("EntryId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("entry_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("file_name");

                    b.Property<string>("ObjectStorageKey")
                        .HasColumnType("longtext")
                        .HasColumnName("object_storage_key");

                    b.HasKey("Id");

                    b.HasIndex("DraftId");

                    b.HasIndex("EntryId");

                    b.ToTable("Attachments", t =>
                        {
                            t.HasCheckConstraint("CK_Attachment_SingleSource", "(entry_id IS NULL AND draft_id IS NOT NULL) OR (entry_id IS NOT NULL AND draft_id IS NULL)");
                        });
                });

            modelBuilder.Entity("AstralDiaryApi.Models.Entities.Draft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("DraftId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("draft_id");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("modified_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("DraftId");

                    b.HasIndex("ModifiedAt");

                    b.HasIndex("UserId");

                    b.ToTable("Drafts");
                });

            modelBuilder.Entity("AstralDiaryApi.Models.Entities.Entry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("deleted_at");

                    b.Property<string>("EntryId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("entry_id");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("modified_at");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("published_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("EntryId");

                    b.HasIndex("UserId");

                    b.ToTable("Entries");
                });

            modelBuilder.Entity("AstralDiaryApi.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("FirebaseUid")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("firebase_uid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AstralDiaryApi.Models.Entities.Attachment", b =>
                {
                    b.HasOne("AstralDiaryApi.Models.Entities.Draft", "Draft")
                        .WithMany("Attachments")
                        .HasForeignKey("DraftId")
                        .HasPrincipalKey("DraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AstralDiaryApi.Models.Entities.Entry", "Entry")
                        .WithMany("Attachments")
                        .HasForeignKey("EntryId")
                        .HasPrincipalKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Draft");

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("AstralDiaryApi.Models.Entities.Draft", b =>
                {
                    b.HasOne("AstralDiaryApi.Models.Entities.User", "User")
                        .WithMany("Drafts")
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AstralDiaryApi.Models.Entities.Entry", b =>
                {
                    b.HasOne("AstralDiaryApi.Models.Entities.User", "User")
                        .WithMany("Entries")
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AstralDiaryApi.Models.Entities.Draft", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("AstralDiaryApi.Models.Entities.Entry", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("AstralDiaryApi.Models.Entities.User", b =>
                {
                    b.Navigation("Drafts");

                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
